### PR TITLE
Change to relative imports

### PR DESCRIPTION
**Pull request by tomasfrtala**
Proposal for making this project as base library for comfortable extending.
Simple demonstration of this new approach can be seen here: https://github.com/tomasfrtala/bitmex-wrapper
**Use case** - one wants to build own assets with keeping updates of original library for potential bug fixing without exhaustive rebuilding after pulling from upstream.

### CODE REVIEW

**Comment by STRML** [comment]
Hi - there should not be any need to rewrite this repository in order to do this.

I've published this as a module on pypi which should help out. Add it to your requirements.txt and let me know if anything else is needed (there might be a need for a change to settings.py).

**Comment by tomasfrtala** [comment]
@STRML thank you, but I have problem during installation:
```
tommy@ubuntu (venv): sudo -H pip install bitmex-market-maker
Collecting bitmex-market-maker
  Using cached bitmex-market-maker-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/bitmex_market_maker.egg-info
    writing requirements to pip-egg-info/bitmex_market_maker.egg-info/requires.txt
    writing top-level names to pip-egg-info/bitmex_market_maker.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/bitmex_market_maker.egg-info/dependency_links.txt
    writing pip-egg-info/bitmex_market_maker.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/bitmex_market_maker.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/bitmex_market_maker.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/bitmex_market_maker.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lde4xu9h/bitmex-market-maker/setup.py", line 24, in <module>
        copyfile(join('market_maker', '_settings_base.py'), 'settings.py')
      File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'market_maker/_settings_base.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lde4xu9h/bitmex-market-maker/
```

**Comment by tomasfrtala** [comment]
Found similar theme here: https://github.com/urwid/urwid/pull/187

**Comment by tomasfrtala** [comment]
@STRML confirming the latest version can successfully satisfy originally proposed solution. Thank you, closing PR.

**Pull request closed without merging**
