### PR TITLE
Use `cumQty` instead of `leavesQty` for executions.

### PR DESCRIPTION
**Pull request by jeteon**
Code currently uses changes in the `leavesQty` attribute to detect order executions. Amending orders (particularly by amending the `leavesQty` attribute) also changes this attribute, however so that there's ambiguity about whether a change in this quantity is actually an execution. I happen to have code that makes amendments in this way so I saw a lot of spam about orders that could not possibly have executed having been executed. 

After looking through some documentation (since I needed to separately track executions) I found that the correct quantity used to indicate executions is `cumQty`. Order executions do decrease `leavesQty` so in most cases the current scheme works out but it is not correct.

### CODE REVIEW

**Comment by STRML** [comment]
Hey - thanks @jeteon. I actually just updated this yesterday and didn't see your PR. This logging is much more robust now to amends. Thanks for the PR!

**Comment by jeteon** [comment]
The new implementation still seems to be incorrect. When I alter an order by increasing `leavesQty` the implementation keeps recording the new position size as an execution. I'm starting to doubt whether its possible to implement a correct websocket implementation for the BitMex API given the level of documentation available. Are there any definitive sources on what BitMex considers `leavesQty`, `cumQty` etc to mean? And yes, I've looked through the online documentation. The closest I've come to a definition of this has been the implementation of others who have used similar terms.

**Comment by STRML** [comment]
Just as a reference (and we'll be beefing up documentation for this in the near future): `cumQty` is the total size of the order, and `leavesQty` is how much is still open. For example:

* Order is placed for `1000`: `cumQty = 1000, leavesQty = 1000`
* 500 executes: `cumQty = 1000, leavesQty = 500`
* Order is amended to `leavesQty: 1000`: `cumQty = 1500, leavesQty = 1000`
* Order is amended to `cumQty: 1200`: `cumQty = 1200, leavesQty = 700`.

**Comment by jeteon** [comment]
Um...I'm not sure if you've done this but if you create an order on the API and then query its details again, you'll see that a new order has `cumQty = 0`. I believe the property you were looking for there is `orderQty` which tracks the total size of the order. `leavesQty` is correctly stated as the number of open contracts on the order and `cumQty` would be the difference between `leavesQty` and `orderQty`. 

I know it may be hard to believe that a random guy on the internet about this but it won't take long at all to try this out yourself to confirm/refute it.

**Comment by STRML** [comment]
You're correct - I even get this jumbled up. I've amended the original comment. `cumQty` is the executed portion.

**Comment by jeteon** [comment]
The documentation states [here](https://www.bitmex.com/api/explorer/#!/Order/Order_getOrders):
> See the [FIX Spec](http://www.onixs.biz/fix-dictionary/5.0.SP2/msgType_D_68.html) for explanations of these fields.

So that's where I went to learn about what the `*Qty` fields mean. For instance for `cumQty`:
http://www.onixs.biz/fix-dictionary/4.0/tagNum_14.html

It's still a little confusing though since there's also the element of whether the API really does comply to a third party spec. That particular set of documentation (on the FIX spec) is also rather difficult to navigate through. It will be immensely helpful once you update the documentation to simply add a paragraph defining each of the `*Qty` fields.

**Comment by jeteon** [comment]
In fact, I believe even just having your amended comment added to the documentation as is would help a ton.

**Comment by STRML** [comment]
We do indeed attempt to follow the FIX spec as closely as possible.

See d68c5c526044f97229af645f6a1a03f9ccb8a3e4 for a fix.

**Comment by jeteon** [comment]
Okay. Btw, do you know a way that would allow for testing against the API? I wanted to try things out whilst thinking about this but ended up doing things which were rather clunky. Its simple enough to create an order on the testnet far from the action, amend it, remove it, etc. Its quite a bit more difficult to catch an order in a partially filled state without having two opposing accounts though.

Its sorta something I was thinking about in terms of setting up tests for my bot. There's an issue I've been experiencing with a drift in accounting for orders that may or may not be related and I wanted to see if there's a way to set up automated tests for this.

**Comment by STRML** [comment]
We generally recommend setting up two Testnet accounts to wash between one another if you want to test execution notifications and so on. I know it's not the most convenient, but aside from offering a fully standalone copy of the exchange, it's the best we can offer. 

After obtaining that data, you could replay it back through your adapter.

**Pull request closed without merging**
