### PR TITLE
discord chat

### PR DESCRIPTION
**Pull request by ak9250**
I think we should have a discord chat to talk about issues and enhancements and any help anyone needs to get started that would minimize the need to create issues unless it is something that is fairly complex. I provided the link for the discord chat in the ReadME I made to help with this.

### CODE REVIEW

**Comment by scottie** [comment]
The invite link is dead, and i think it would be best to keep discussion on issues to github where they belong and can be correctly tracked....

**Comment by ak9250** [comment]
dont know why that happened, it was working before and a couple people already joined. Yes issues are on github and often not answered for a while.... Discord can take care of trivial issues in real time and people can discuss other things as well that are not directly related to issues. Thanks for your feedback and I have updated the link to a working link.

**Comment by scottie** [comment]
If you really insist on it, please set your discord link to "not expire", and make a new one, for as i said that one is dead.

**Comment by ak9250** [comment]
My bad, I just noticed invite links expire after 1 day by default, changed the setting to never and added a new link. Thanks for pointing that out :).

**Comment by metaperl** [comment]
The README does not reflect this patch to list a Discord server...

**Comment by ak9250** [comment]
@metaperl I dont understand, what is not working?

**Pull request closed without merging**
